### PR TITLE
Improve table schema guessing SQL

### PR DESCRIPTION
**Pull request by oblitorum**

### CODE REVIEW

**Comment by gordan-bobic** [comment]
Shouldn't this:
```
SELECT t.table_schema, tt.schema_count
		FROM information_schema.tables t
		JOIN (
			SELECT table_name, COUNT(table_schema) AS schema_count
			FROM information_schema.tables
			GROUP BY table_name
		) tt ON t.table_name = tt.table_name
		JOIN (
			SELECT table_schema, COALESCE(SUM(table_rows), 0) AS table_rows
			FROM information_schema.tables
			GROUP BY table_schema
		) st ON t.table_schema = st.table_schema
		WHERE t.table_name IN (%s)
		ORDER BY tt.schema_count ASC, t.table_rows IS NULL ASC, t.table_rows DESC, st.table_rows DESC
		LIMIT 1;
```
be something like this:
```
        SELECT table_schema, COUNT(table_name) AS table_count, COALESCE(SUM(table_rows)) AS table_rows
        FROM information_schema.tables
        WHERE table_name IN (%s)
        GROUP BY table_schema
        ORDER BY schema_count ASC, table_rows DESC
        LIMIT 1;
```

I may be wrong, so please sanity check what I'm doing because I'm not sure I understand correctly what the query is intended to do with the extra join. Obviously this returns 3 columns rather than 2, but I think we only really need the first, unless I am missing something (and there is a good chance that I am missing something).

The idea is to get the schema that matches most of the tables mentioned in the query, and as a tie-breaker, pick the schema with most rows across all of the tables mentioned in the schema. Right?

**Comment by oblitorum** [comment]
> Shouldn't this:
> 
> ```
> SELECT t.table_schema, tt.schema_count
> 		FROM information_schema.tables t
> 		JOIN (
> 			SELECT table_name, COUNT(table_schema) AS schema_count
> 			FROM information_schema.tables
> 			GROUP BY table_name
> 		) tt ON t.table_name = tt.table_name
> 		JOIN (
> 			SELECT table_schema, COALESCE(SUM(table_rows), 0) AS table_rows
> 			FROM information_schema.tables
> 			GROUP BY table_schema
> 		) st ON t.table_schema = st.table_schema
> 		WHERE t.table_name IN (%s)
> 		ORDER BY tt.schema_count ASC, t.table_rows IS NULL ASC, t.table_rows DESC, st.table_rows DESC
> 		LIMIT 1;
> ```
> 
> be something like this:
> 
> ```
>         SELECT table_schema, COUNT(table_name) AS table_count, COALESCE(SUM(table_rows)) AS table_rows
>         FROM information_schema.tables
>         WHERE table_name IN (%s)
>         GROUP BY table_schema
>         ORDER BY schema_count ASC, table_rows DESC
>         LIMIT 1;
> ```
> 
> I may be wrong, so please sanity check what I'm doing because I'm not sure I understand correctly what the query is intended to do with the extra join. Obviously this returns 3 columns rather than 2, but I think we only really need the first, unless I am missing something (and there is a good chance that I am missing something).
> 
> The idea is to get the schema that matches most of the tables mentioned in the query, and as a tie-breaker, pick the schema with most rows across all of the tables mentioned in the schema. Right?

OK, now I understand the logic, I was stuck in the previous logic -> take the schema from the table that has least ambiguous schemas, and as a tie-breaker, take the schema from the table that has most rows.

But there seems some typoes in the fixed query, shouldn't it be:

```diff
SELECT table_schema, COUNT(table_name) AS table_count, COALESCE(SUM(table_rows)) AS table_rows
FROM information_schema.tables
WHERE table_name IN (%s)
GROUP BY table_schema
- ORDER BY schema_count ASC, table_rows DESC
+ ORDER BY table_count DESC, table_rows DESC
LIMIT 1;
```

**Comment by gordan-bobic** [comment]
I meant:
```
- mentioned in the schema
+ mentioned in the query
```
You are right about my query typo. How about this:
```
SELECT table_schema, COUNT(*) AS table_count, SUM(ifnull(table_rows,0)) AS table_rows
FROM information_schema.tables
WHERE table_name IN (%s)
GROUP BY table_schema
ORDER BY table_count DESC, table_rows DESC
LIMIT 1;
```

**Comment by oblitorum** [comment]
Sounds good, pushed the changes

**Pull request merged**
