### PR TITLE
Fix guessing database process

### PR DESCRIPTION
**Pull request by oblitorum**

### CODE REVIEW

**Comment by gordan-bobic** [comment]
Why do we need to know of it is ambiguous? Secondary sort in table_rows is as good as we are going to get. What can we even do just from knowing it is ambiguous?

**Comment by oblitorum** [comment]
image

Don't we still need this feature? To tell people we are not 100% sure about the schema in this situation.

**Comment by gordan-bobic** [comment]
I see , so this is just to highlight to the user that we are guessing, and we found more than one schema that "could fit"? Fair enough then.

Will this work when we are dealing with cross-schema joins? E.g.
```
select *
from schema1.table1
join schema2.table2 ON ...
```
?

**Comment by oblitorum** [comment]
If all schemas are explicit, they should be parsed during the parsing process and so the guessing process doesn't needed.

But if one of the schema is imexplicit because the schema is current used, e.g.

```
select *
from table1
join schema2.table2 ON ...
```

and the parsing process somehow failed to get the current used schema, then the **schema2** is used with current code base, it doesn't invoke the guessing process either.

Now I realize we shouldn't use the explicit schema blindly, I didn't think of this situation before, I will send some patches for this problem

**Comment by gordan-bobic** [comment]
Yes, if anything, if schema is specified in a query, that is unusual and almost always implies that other tables are NOT from the same schema. So it is a contra-indication rather than an indication.

**Comment by oblitorum** [comment]
OK, this situation is now considered

**Pull request merged**
